import Head from "next/head";
import About from "../components/about";
import Footer from "../components/footer";
import Header from "../components/header";
import JoinTo from "../components/jointo";
import Landing from "../components/landing";
import Projects from "../components/projects";
import SubmitIdea from "../components/submit_idea";

export default function Home() {
    return (
        <div>
            <Head>
                <title>Builtree</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <main className="relative">
                <Landing />
                <About />
                <JoinTo />
                <SubmitIdea />
                <Projects />
                <Footer />
            </main>
        </div>
    );
}
